import type { WizardStep } from '@/types/wizard'

export const wizardSteps: WizardStep[] = [
  {
    id: 'putovanje',
    title: 'Podaci o putovanju',
    fields: [
      {
        id: 'broj_naloga',
        label: 'Broj putnog naloga',
        type: 'text',
        required: false,
        placeholder: 'npr. PN-2026-001',
        helperText: 'Redni broj naloga — opciono',
      },
      {
        id: 'datum_izdavanja',
        label: 'Datum izdavanja',
        type: 'date',
        required: true,
      },
      {
        id: 'svrha_putovanja',
        label: 'Svrha putovanja',
        type: 'text',
        required: true,
        placeholder: 'npr. Poseta klijentu, Sajam, Seminar',
      },
      {
        id: 'polaziste',
        label: 'Mesto polaska',
        type: 'text',
        required: true,
        placeholder: 'npr. Beograd',
      },
      {
        id: 'odrediste',
        label: 'Odredište (mesto dolaska)',
        type: 'text',
        required: true,
        placeholder: 'npr. Novi Sad',
      },
      {
        id: 'datum_polaska',
        label: 'Datum polaska',
        type: 'date',
        required: true,
      },
      {
        id: 'datum_povratka',
        label: 'Datum povratka',
        type: 'date',
        required: false,
      },
      {
        id: 'napomena_ruta',
        label: 'Napomena uz rutu',
        type: 'text',
        required: false,
        placeholder: 'npr. Obilazak više lokacija',
        helperText: 'Opciono — prikazuje se u koloni "Napomena" tabele kretanja',
      },
    ],
  },
  {
    id: 'vozac',
    title: 'Podaci o vozaču',
    fields: [
      {
        id: 'ime_vozaca',
        label: 'Ime i prezime vozača',
        type: 'text',
        required: true,
        placeholder: 'npr. Marko Marković',
      },
      {
        id: 'pozicija_vozaca',
        label: 'Radno mesto / pozicija',
        type: 'text',
        required: false,
        placeholder: 'npr. Menadžer prodaje',
      },
    ],
  },
  {
    id: 'vozilo',
    title: 'Podaci o vozilu',
    fields: [
      {
        id: 'marka_model',
        label: 'Marka i model vozila',
        type: 'text',
        required: true,
        placeholder: 'npr. Volkswagen Golf 8',
      },
      {
        id: 'registarski_broj',
        label: 'Registarski broj',
        type: 'text',
        required: true,
        placeholder: 'npr. BG 123-AB',
      },
      {
        id: 'km_pocetak',
        label: 'Stanje km-sata pri polasku',
        type: 'text',
        required: false,
        placeholder: 'npr. 48250',
        helperText: 'Opciono — unesite ako želite na nalogu',
      },
    ],
  },
  {
    id: 'firma_troskovi',
    title: 'Firma i troškovi',
    fields: [
      {
        id: 'naziv_firme',
        label: 'Naziv firme',
        type: 'text',
        required: true,
        placeholder: 'npr. Moja Firma d.o.o.',
      },
      {
        id: 'adresa_firme',
        label: 'Adresa firme',
        type: 'text',
        required: false,
        placeholder: 'npr. Knez Mihailova 10, Beograd',
      },
      {
        id: 'pib',
        label: 'PIB firme',
        type: 'text',
        required: false,
        placeholder: 'npr. 123456789',
      },
      {
        id: 'ovlasceno_lice',
        label: 'Ovlašćeno lice (direktor / nadređeni)',
        type: 'text',
        required: true,
        placeholder: 'npr. Jovana Jovanović',
        helperText: 'Lice koje odobrava i potpisuje nalog',
      },
      {
        id: 'dnevnica',
        label: 'Dnevnica na teret firme',
        type: 'toggle',
        required: false,
        defaultValue: false,
      },
      {
        id: 'gorivo_na_teret_firme',
        label: 'Gorivo na teret firme',
        type: 'toggle',
        required: false,
        defaultValue: false,
      },
      {
        id: 'smestaj',
        label: 'Smeštaj na teret firme',
        type: 'toggle',
        required: false,
        defaultValue: false,
      },
      {
        id: 'ostali_troskovi',
        label: 'Ostali troškovi',
        type: 'text',
        required: false,
        placeholder: 'npr. Parking, putarina, reprezentacija',
        helperText: 'Opciono — kratak opis ostalih troškova',
      },
    ],
  },
]
