import type { WizardStep } from '@/types/wizard'

export const wizardSteps: WizardStep[] = [
  {
    id: 'putovanje',
    title: 'Podaci o putovanju',
    fields: [
      {
        id: 'broj_naloga',
        label: 'Broj putnog naloga',
        type: 'text',
        required: false,
        placeholder: 'npr. PN-2026-001',
        helperText: 'Redni broj naloga — opciono',
      },
      {
        id: 'datum_izdavanja',
        label: 'Datum izdavanja',
        type: 'date',
        required: true,
      },
      {
        id: 'svrha_putovanja',
        label: 'Svrha putovanja',
        type: 'text',
        required: true,
        placeholder: 'npr. Poslovna poseta klijentu, Seminar, Sajam',
      },
      {
        id: 'destinacija',
        label: 'Destinacija (grad / država)',
        type: 'text',
        required: true,
        placeholder: 'npr. Beograd, Novi Sad, Frankfurt',
      },
      {
        id: 'datum_polaska',
        label: 'Datum polaska',
        type: 'date',
        required: true,
      },
      {
        id: 'datum_povratka',
        label: 'Datum povratka',
        type: 'date',
        required: true,
      },
    ],
  },
  {
    id: 'zaposleni',
    title: 'Podaci o zaposlenom',
    fields: [
      {
        id: 'ime_prezime',
        label: 'Ime i prezime zaposlenog',
        type: 'text',
        required: true,
        placeholder: 'npr. Marko Marković',
      },
      {
        id: 'pozicija',
        label: 'Radno mesto / pozicija',
        type: 'text',
        required: true,
        placeholder: 'npr. Menadžer prodaje',
      },
      {
        id: 'prevozno_sredstvo',
        label: 'Prevozno sredstvo',
        type: 'dropdown',
        required: true,
        options: [
          { value: 'Službeno vozilo', label: 'Službeno vozilo' },
          { value: 'Sopstveni automobil', label: 'Sopstveni automobil' },
          { value: 'Avion', label: 'Avion' },
          { value: 'Voz', label: 'Voz' },
          { value: 'Autobus', label: 'Autobus' },
          { value: 'Kombinovano', label: 'Kombinovano' },
        ],
      },
      {
        id: 'registarski_broj',
        label: 'Registarski broj vozila',
        type: 'text',
        required: false,
        placeholder: 'npr. BG 123-AB',
        helperText: 'Popunite samo ako se koristi vozilo',
      },
    ],
  },
  {
    id: 'firma',
    title: 'Podaci o firmi',
    fields: [
      {
        id: 'naziv_firme',
        label: 'Naziv firme',
        type: 'text',
        required: true,
        placeholder: 'npr. Moja Firma d.o.o.',
      },
      {
        id: 'adresa_firme',
        label: 'Adresa firme',
        type: 'text',
        required: false,
        placeholder: 'npr. Knez Mihailova 10, Beograd',
      },
      {
        id: 'pib',
        label: 'PIB',
        type: 'text',
        required: false,
        placeholder: 'npr. 123456789',
      },
      {
        id: 'zastupnik',
        label: 'Ovlašćeno lice / direktor',
        type: 'text',
        required: false,
        placeholder: 'npr. Jovana Jovanović',
        helperText: 'Potpis na nalogu — opciono',
      },
    ],
  },
  {
    id: 'troskovi',
    title: 'Troškovi putovanja',
    fields: [
      {
        id: 'dnevnica',
        label: 'Dnevnica (RSD)',
        type: 'number',
        required: false,
        placeholder: 'npr. 2750',
        helperText: 'Neoporeziv iznos za 2026: 2.750 RSD/dan (zemlja) ili do 50 EUR/dan (inostranstvo)',
      },
      {
        id: 'broj_dnevnica',
        label: 'Broj dnevnica',
        type: 'number',
        required: false,
        placeholder: 'npr. 2',
      },
      {
        id: 'troskovi_prevoza',
        label: 'Troškovi prevoza (RSD)',
        type: 'number',
        required: false,
        placeholder: 'npr. 5000',
      },
      {
        id: 'troskovi_smestaja',
        label: 'Troškovi smeštaja (RSD)',
        type: 'number',
        required: false,
        placeholder: 'npr. 12000',
      },
      {
        id: 'ostali_troskovi',
        label: 'Ostali troškovi (RSD)',
        type: 'number',
        required: false,
        placeholder: 'npr. 1500',
      },
      {
        id: 'napomena',
        label: 'Napomena',
        type: 'textarea',
        required: false,
        placeholder: 'Dodatne napomene ili opis troškova...',
      },
    ],
  },
]
